#!/usr/bin/env bash
# A bash script that displays subdomains info

domaininfo()
{
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ "$#" == 1 ]
then
    domaininfo "$1" "www"
    domaininfo "$1" "lb-01"
    domaininfo "$1" "web-01"
    domaininfo "$1" "web-02"
elif [ "$#" == 2 ]
then
    domaininfo "$1" "$2"
fi
