#!/usr/bin/env bash
# A bash script that installs nginx and configures it to listen on port 80
sudo apt-get update -y 
sudo apt-get upgrade -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
