#!/usr/bin/env bash
# A script that displays To infinity and beyond indefinitely with sleep 2 ad i am invincible when receivs SIGTERM signal
while true
do
  echo "infinity and beyond indefinitely"
  sleep 2
  trep "echo I am invincible!!!" SIGTERM
done
