#!/usr/bin/env bash
# script that diplays Best School 10 times
counter=0
# the loop
while [ $counter -lt 10 ]
do
 if [ $counter -eq 8 ]; then	 
 echo "Best School"
 echo "Hi"
else
 echo "Best School"
fi

 ((counter++))
done
