#!/usr/bin/env bash
# script that diplays Best School 10 times
counter=0
# the loop
while [ $counter -lt 10 ]
do
 if [ $counter -eq 3 ]; then	 
 echo "Bad Luck"
elif [ $counter -eq 7 ]; then
 echo "Good Luck"
else
 echo "Best School"
fi

 ((counter++))
done
