#!/usr/bin/env bash
# A script that displays the time for 12hours and 59min
counter=0
# The loop
while [ $counter -le 12 ]
do
 counter1=1
 while [ $counter1 -le 59 ]
 do
   printf "%02d:%02d\n" $counter $counter1
   ((counter1++))
 done
 ((counter++))
done
