#!/usr/bin/env bash
# A script that gives you information about the school file
path="school"
# check if the file exists
if [ -e "$path" ]; then
  echo "school file exists"
  if [ -s "$path" ]; then
    echo "school file is not empty"
    if [-f "$path" ]; then
      echo "school is a regular file"
    fi
   else
     echo "school file is empty"
   fi
else
  echo "school file does not exist"
fi
