#!/usr/bin/env bash
# A bash that runs nginx as nginx user.
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/conf.d/default.conf
sed -i 's/listen [::]:80;/listen [::]:8080;/' /etc/nginx/conf.d/default.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
