#!/usr/bin/env bash
# A bash that runs nginx as nginx user.
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen\s*80;/a listen 8080;' /etc/nginx/sites-available/default
service nginx start
echo "Nginx is now running as the nginx user and listening on port 8080."